---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Safe Web for work"
keywords:    "safe, web, for, work, business, work, office, browser, whitelist, sandbox, control, access, limited, best, app, ios, hotel, airport"
description: "Safe Web for work is a web browser for iOS devices."
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA-25289053-7 ## put YOUR key here to enable tracking! (blank to disable)
appstore_link: "https://itunes.apple.com/app/safe-web-for-business/id1114000127?ct=web&mt=8"


### template colors, used site-wide via css ###
colors:
  red:       '#5A5151'      
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  gtgold:    '#E0A01F'
  gtnavy:    '#01192F'
  gtmetallic: '#A08452'

kramdown:
  auto_ids:  false

